// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmLKdfo3crflJlPbgNPfa9JU2rNlHFj2g',
    appId: '1:155928426735:web:16c951b2ccdc7cd17f831a',
    messagingSenderId: '155928426735',
    projectId: 'invoice-ea5f8',
    authDomain: 'invoice-ea5f8.firebaseapp.com',
    storageBucket: 'invoice-ea5f8.firebasestorage.app',
    measurementId: 'G-P7V41Y0849',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQgQDMDjeVQktRoyQrdAfPrADbDYq3SgQ',
    appId: '1:155928426735:android:a754fff5a278b4e97f831a',
    messagingSenderId: '155928426735',
    projectId: 'invoice-ea5f8',
    storageBucket: 'invoice-ea5f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAdK4TpMAd4MpBcSacrmyZGFAoVJaGd34',
    appId: '1:155928426735:ios:0724a9f68eaa8dad7f831a',
    messagingSenderId: '155928426735',
    projectId: 'invoice-ea5f8',
    storageBucket: 'invoice-ea5f8.firebasestorage.app',
    iosClientId: '155928426735-ph13lhtl0p0nbm00sspg9kv6c15rtbot.apps.googleusercontent.com',
    iosBundleId: 'com.example.invoice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAdK4TpMAd4MpBcSacrmyZGFAoVJaGd34',
    appId: '1:155928426735:ios:0724a9f68eaa8dad7f831a',
    messagingSenderId: '155928426735',
    projectId: 'invoice-ea5f8',
    storageBucket: 'invoice-ea5f8.firebasestorage.app',
    iosClientId: '155928426735-ph13lhtl0p0nbm00sspg9kv6c15rtbot.apps.googleusercontent.com',
    iosBundleId: 'com.example.invoice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmLKdfo3crflJlPbgNPfa9JU2rNlHFj2g',
    appId: '1:155928426735:web:381bcbe8d70d6b507f831a',
    messagingSenderId: '155928426735',
    projectId: 'invoice-ea5f8',
    authDomain: 'invoice-ea5f8.firebaseapp.com',
    storageBucket: 'invoice-ea5f8.firebasestorage.app',
    measurementId: 'G-V1VHG182PZ',
  );
}
